name: "Named Forward Zone: Machines"

# Source template file.  This is what will be put into a single or multiple output files, depending on path
template: example-templates/prod_named_master/zone_forward_machine

# Data source spec is from in specs/datasources.yaml
datasource: ops

# SQL query or JSON/YAML key filter, depending on datasource type
filter: "SELECT * FROM machine WHERE service NOT IN (22) AND location = 3 ORDER BY name"


