name: "Named Reverse Zone: Static"

# Source template file.  This is what will be put into a single or multiple output files, depending on path
template wrapper: example-templates/prod_named_master/zone_reverse_static

